DROP TABLE IF EXISTS SHOW_EPISODE_COSTS;

CREATE TABLE SHOW_EPISODE_COSTS (
  ID NUMERIC(16) AUTO_INCREMENT,
  SHOW_ID NUMERIC(16),
  EPISODE_CODE VARCHAR(8),
  AMOUNT NUMERIC(16),
  PRIMARY KEY (ID)
);
INSERT INTO SHOW_EPISODE_COSTS (SHOW_ID, EPISODE_CODE, AMOUNT) VALUES (1,'101',200);
INSERT INTO SHOW_EPISODE_COSTS (SHOW_ID, EPISODE_CODE, AMOUNT) VALUES (1,'101',100);
INSERT INTO SHOW_EPISODE_COSTS (SHOW_ID, EPISODE_CODE, AMOUNT) VALUES (1,'101',300);
INSERT INTO SHOW_EPISODE_COSTS (SHOW_ID, EPISODE_CODE, AMOUNT) VALUES (2,'101',200);
INSERT INTO SHOW_EPISODE_COSTS (SHOW_ID, EPISODE_CODE, AMOUNT) VALUES (2,'102',300);
INSERT INTO SHOW_EPISODE_COSTS (SHOW_ID, EPISODE_CODE, AMOUNT) VALUES (2,'103',200);
INSERT INTO SHOW_EPISODE_COSTS (SHOW_ID, EPISODE_CODE, AMOUNT) VALUES (2,'101',200);
INSERT INTO SHOW_EPISODE_COSTS (SHOW_ID, EPISODE_CODE, AMOUNT) VALUES (2,'001',200);
INSERT INTO SHOW_EPISODE_COSTS (SHOW_ID, EPISODE_CODE, AMOUNT) VALUES (2,'001',100);

-- for movie 2, amortized cost per episode is 100,
-- 101 500
-- 102 400
-- 103 300




