DROP TABLE IF EXISTS SHOW_EPISODE_COSTS;

CREATE TABLE SHOW_EPISODE_COSTS (
  ID VARCHAR(16),
  EPISODE_CODE VARCHAR(8),
  AMOUNT VARCHAR(16)
);
INSERT INTO SHOW_EPISODE_COSTS (ID, EPISODE_CODE, AMOUNT) VALUES (1,101,200);
INSERT INTO SHOW_EPISODE_COSTS (ID, EPISODE_CODE, AMOUNT) VALUES (1,101,100);
INSERT INTO SHOW_EPISODE_COSTS (ID, EPISODE_CODE, AMOUNT) VALUES (1,101,300);
INSERT INTO SHOW_EPISODE_COSTS (ID, EPISODE_CODE, AMOUNT) VALUES (2,101,200);
INSERT INTO SHOW_EPISODE_COSTS (ID, EPISODE_CODE, AMOUNT) VALUES (2,102,300);
INSERT INTO SHOW_EPISODE_COSTS (ID, EPISODE_CODE, AMOUNT) VALUES (2,103,200);
INSERT INTO SHOW_EPISODE_COSTS (ID, EPISODE_CODE, AMOUNT) VALUES (2,101,200);




